# Generated by Django 4.2.16 on 2026-04-22 15:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', message='Session must be in format: 2024/2025')])),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_years', models.IntegerField(choices=[(4, '4 Years'), (5, '5 Years')], default=4)),
                ('hod', models.CharField(blank=True, help_text='Name of the HOD', max_length=200)),
                ('current_levels', models.IntegerField(default=4, help_text='Number of levels in department (e.g., 4 for 100-400 level)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faculty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('dean', models.CharField(blank=True, help_text='Name of the Dean', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sug_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fees_description', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='portal.department')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicsession')),
            ],
            options={
                'ordering': ['level', 'semester'],
                'unique_together': {('department', 'level', 'semester', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('current_level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default='100', max_length=3)),
                ('current_semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], default='First', max_length=10)),
                ('entry_year', models.CharField(blank=True, help_text='Year of entry (e.g., 2022)', max_length=4)),
                ('mode_of_entry', models.CharField(choices=[('UTME', 'UTME'), ('DE', 'Direct Entry')], default='UTME', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('profile_completed', models.BooleanField(default=False)),
                ('cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('total_credit_units_earned', models.IntegerField(default=0)),
                ('total_grade_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('academic_standing', models.CharField(choices=[('Good', 'Good Standing'), ('Probation', 'Probation'), ('Withdrawn', 'Withdrawn')], default='Good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('result_entry_start', models.DateField(blank=True, null=True)),
                ('result_entry_end', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='portal.academicsession')),
            ],
            options={
                'ordering': ['-session__name', 'semester'],
                'unique_together': {('session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='portal.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='portal.faculty'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('credit_units', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_general_studies', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portal.department')),
                ('prerequisites', models.ManyToManyField(blank=True, to='portal.course')),
            ],
            options={
                'ordering': ['level', 'semester', 'code'],
                'unique_together': {('department', 'code', 'level', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('exam_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_score', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, help_text='Legacy score field (mirrors total_score)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(choices=[('A', 'A (70-100)'), ('B', 'B (60-69)'), ('C', 'C (50-59)'), ('D', 'D (45-49)'), ('E', 'E (40-44)'), ('F', 'F (0-39)')], editable=False, max_length=1)),
                ('grade_point', models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved by Lecturer'), ('verified', 'Verified by HOD'), ('published', 'Published')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.studentprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_results', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__level', 'course__semester', 'course__code'],
                'unique_together': {('student', 'course', 'session')},
            },
        ),
        migrations.CreateModel(
            name='GPAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_credits', models.IntegerField()),
                ('total_grade_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_results', to='portal.studentprofile')),
            ],
            options={
                'ordering': ['-session__name', '-semester__semester'],
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'faculty')},
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_carryover', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='portal.studentprofile')),
            ],
            options={
                'ordering': ['-session__name', 'course__code'],
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coordinator', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('lecturer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicsession')),
            ],
            options={
                'ordering': ['-session__name', 'course__code'],
                'unique_together': {('lecturer', 'course', 'session')},
            },
        ),
    ]
